(define-module (byggsteg-preferences)
  #:use-module (ice-9 time)
  #:use-module (ice-9 format)
  #:use-module (ice-9 string-fun)
  )

(define-public job-failure-location "/var/log/byggsteg/job-failure/")
(define-public job-success-location "/var/log/byggsteg/job-success/")
(define-public job-clone-location "/var/log/byggsteg/job-clone/")
(define-public job-log-location "/var/log/byggsteg/job-log/")
